package net.ilabs.skillbrowser.domain.model;

// Generated 23 sept. 2013 15:55:50 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Skill generated by hbm2java
 */

@Entity
@Table(name = "skill", catalog = "skillbrowser", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Skill implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer skillId;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Skill() {
	}

	public Skill(String name) {
		this.name = name;
	}

	public Skill(String name, Set<User> users) {
		this.name = name;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "skill_id", unique = true, nullable = false)
	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "skills", cascade = { CascadeType.ALL })
	public Set<User> getUsers() {
		return this.users;
		
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
